elasticsearch:
   build: es
   restart: always
   ports:
      - 9300:9300
      - 9200:9200

flume:
   build: flume
   restart: always
   links:
     - elasticsearch

kibana:
   build: kibana
   restart: always
   ports:
      - 5601:5601
   links:
      - elasticsearch
